---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  uri:
    url: http://{{ prometheus_address }}:{{ prometheus_port }}{{ prometheus_route_prefix }}/-/reload
    method: "POST"
